---

- name: Download site file
  get_url:
    url: https://github.com/do-community/html_demo_site/archive/refs/heads/main.zip
    dest: "{{ document_root }}" 

- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: /var/www/html_demo_site-main.zip
    dest: "{{ document_root }}"

- name: install ngnix
  package:
    name: nginx
    state: latest

- name: enable ngnix
  service:
    name: nginx
    enabled: true
    state: started
  


- name: Apply Nginx template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Restart Nginx

- name: Enable new site
  file:
   src: /etc/nginx/sites-available/default
   dest: /etc/nginx/sites-enabled/default
   state: link
  notify: Restart Nginx
